
[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://basiskaart:insecure@database/basiskaart"
name = "dbconn"
default = true


[grid]
predefined = "web_mercator"

[[tileset]]
name = "basiskaart_wm"
extent = [4.49712476945351, 52.1630507756721, 5.60867873764429, 52.6147675426215]
cache_limits = {minzoom = 0, maxzoom = 22, no_cache = false}

[[tileset.layer]]
name = "bgt_vw_waterdeel_vlak"
table_name = "bgt.bgt_vw_waterdeel_vlak"
geometry_field = "geometrie"
geometry_type = "MULTIPOLYGON"
minzoom = 8
maxzoom = 22
srid = 28992
buffer_size = 10
    [[tileset.layer.query]]
    minzoom = 8
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 8 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""

[[tileset.layer]]
name = "bgt_vw_waterdeel_lijn"
table_name = "bgt.bgt_vw_waterdeel_lijn"
geometry_field = "geometrie"
geometry_type = "MULTILINESTRING"
srid = 28992
buffer_size = 1
minzoom = 12
maxzoom = 22
    [[tileset.layer.query]]
    minzoom = 12
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_lijn WHERE geometrie && !bbox! AND minzoom >= 12 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_lijn WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_waterdeel_lijn WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""

[[tileset.layer]]
name = "bgt_vw_terreindeel_vlak"
table_name = "bgt.bgt_vw_terreindeel_vlak"
geometry_field = "geometrie"
geometry_type = "MULTIPOLYGON"
srid = 28992
buffer_size = 10
    [[tileset.layer.query]]
    minzoom = 8
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_terreindeel_vlak WHERE geometrie && !bbox! AND minzoom >= 8 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_terreindeel_vlak WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_terreindeel_vlak WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""

[[tileset.layer]]
name = "bgt_vw_wegdeel_vlak"
table_name = "bgt.bgt_vw_wegdeel_vlak"
geometry_field = "geometrie"
geometry_type = "MULTIPOLYGON"
srid = 28992
buffer_size = 10
    [[tileset.layer.query]]
    minzoom = 8
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,subtype,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 8 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,subtype,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,subtype,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_vlak WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""


[[tileset.layer]]
name = "bgt_vw_spoor_lijn"
table_name = "bgt.bgt_vw_spoor_lijn"
geometry_field = "geometrie"
geometry_type = "MULTILINESTRING"
srid = 28992
buffer_size = 1
    [[tileset.layer.query]]
    minzoom = 11
    maxzoom = 12
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_spoor_lijn WHERE geometrie && !bbox! AND minzoom = 11 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 13
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_spoor_lijn WHERE geometrie && !bbox! AND minzoom >= 11 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_spoor_lijn WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_spoor_lijn WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""

[[tileset.layer]]
name = "bgt_vw_inrichtingselement_vlak"
table_name = "bgt.bgt_vw_inrichtingselement_vlak"
geometry_field = "geometrie"
geometry_type = "MULTIPOLYGON"
srid = 28992
buffer_size = 0
[[tileset.layer.query]]
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_inrichtingselement_vlak WHERE geometrie && !bbox! AND minzoom <= !zoom! AND !zoom! <= maxzoom"""

[[tileset.layer]]
name = "bgt_vw_gebouw_vlak"
geometry_field = "geometrie"
geometry_type = "MULTIPOLYGON"
minzoom = 8
maxzoom = 22
srid = 28992
buffer_size = 10
    [[tileset.layer.query]]
    minzoom = 8
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_gebouw_vlak WHERE geometrie && !bbox! AND minzoom >= 8 AND maxzoom <= 13"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_gebouw_vlak WHERE geometrie && !bbox! AND minzoom >= 14 AND maxzoom <= 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 22
    sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_gebouw_vlak WHERE geometrie && !bbox! AND minzoom >= 16 AND maxzoom <= 22"""

[[tileset.layer]]
name = "bgt_vw_wegdeel_lijn"
table_name = "bgt.bgt_vw_wegdeel_lijn"
geometry_field = "geometrie"
geometry_type = "MULTILINESTRING"
minzoom = 8
maxzoom = 15
srid = 28992
buffer_size = 1
    [[tileset.layer.query]]
    minzoom = 8
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid::TEXT,type,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_lijn WHERE geometrie && !bbox! AND minzoom >= 8 AND maxzoom <= 13 OR type = 'autosnelweg'"""
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 14
    sql = """SELECT geometrie,identificatie_lokaalid::TEXT,type,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_lijn WHERE geometrie && !bbox! AND maxzoom = 15"""
    [[tileset.layer.query]]
    minzoom = 15
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid::TEXT,type,relatievehoogteligging FROM bgt.bgt_vw_wegdeel_lijn WHERE geometrie && !bbox! AND maxzoom = 15"""

# [[tileset.layer]]
# name = "road_names"
# table_name = "bgt.bgt_vw_wegdeel_lijn"
# geometry_field = "geometrie"
# geometry_type = "MULTILINESTRING"
# minzoom = 14
# maxzoom = 16
# srid = 28992
# buffer_size = 1
#     [[tileset.layer.query]]
#     minzoom = 14
#     maxzoom = 16
#     sql = """SELECT geometrie,identificatie_lokaalid::TEXT,type,wegnaam,wegnummer FROM bgt.bgt_vw_wegdeel_lijn WHERE geometrie && !bbox! AND minzoom = 14 AND maxzoom = 15"""

[[tileset.layer]]
name = "labels_punt"
geometry_field = "geometrie"
geometry_type = "POINT"
srid = 28992
buffer_size = 20
    [[tileset.layer.query]]
    minzoom = 16
    sql = """SELECT geometrie,identificatie_lokaalid,type,tekst,hoek FROM bgt.bgt_vw_labels WHERE geometrie && !bbox!"""

[[tileset.layer]]
name = "labels_vlak"
geometry_field = "geometrie"
geometry_type = "POLYGON"
srid = 28992
buffer_size = 1
    [[tileset.layer.query]]
    minzoom = 12
    maxzoom = 12
    sql = """SELECT geometrie,identificatie_lokaalid,type FROM bgt.bgt_vw_labels_vlak WHERE geometrie && !bbox! AND minzoom = 12 AND maxzoom = 12"""
    [[tileset.layer.query]]
    minzoom = 13
    maxzoom = 13
    sql = """SELECT geometrie,identificatie_lokaalid,type FROM bgt.bgt_vw_labels_vlak WHERE geometrie && !bbox! AND minzoom = 13 AND maxzoom = 13"""    
    [[tileset.layer.query]]
    minzoom = 14
    maxzoom = 15
    sql = """SELECT geometrie,identificatie_lokaalid,type FROM bgt.bgt_vw_labels_vlak WHERE geometrie && !bbox! AND minzoom = 14 AND maxzoom = 15"""
    [[tileset.layer.query]]
    minzoom = 16
    maxzoom = 16
    sql = """SELECT geometrie,identificatie_lokaalid,type FROM bgt.bgt_vw_labels_vlak WHERE geometrie && !bbox! AND minzoom = 16 AND maxzoom = 16"""

#   [[tileset.layer]]
#   name = "bgt_vw_inrichtingselement_lijn"
#   table_name = "bgt.bgt_vw_inrichtingselement_lijn"
#   geometry_field = "geometrie"
#   geometry_type = "MULTILINESTRING"
#   srid = 28992
#   buffer_size = 0
#   #make_valid = true
#   simplify = true
#   query_limit = 1000
#   #[[tileset.layer.query]]
#   #sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_inrichtingselement_lijn WHERE geometrie && !bbox!"""
#   [[tileset.layer]]
#   name = "bgt_vw_inrichtingselement_punt"
#   table_name = "bgt.bgt_vw_inrichtingselement_punt"
#   geometry_field = "geometrie"
#   geometry_type = "MULTIPOINT"
#   srid = 28992
#   buffer_size = 0
#   #make_valid = true
#   simplify = true
#   query_limit = 1000
#   #[[tileset.layer.query]]
#   #sql = """SELECT geometrie,identificatie_lokaalid,type,relatievehoogteligging FROM bgt.bgt_vw_inrichtingselement_punt WHERE geometrie && !bbox!"""

#[cache.file]
#base = "/tmp/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767

#[cache.file]
# base = "/var/cache/mvtcache"

[[webserver.static]]
path = "/static"
dir = "/static"

